language: node_js
node_js:
  - '7'
sudo: false
script:
  - $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" && make travis-deploy
before_install:
  - openssl aes-256-cbc -K $encrypted_e8c0cd5f9239_key -iv $encrypted_e8c0cd5f9239_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - git config --global user.name "publisher"
  - git config --global user.email "publisher@git.hub"
